### PR TITLE
Added flag to run files which do not have labels in first line

### PR DESCRIPTION
**Pull request by KordianD**
I wanted to run this program on my csv which does not have labels in the first line and it crashed.
I have added one flag  --nolabel which tells that file does not have labels and uses whole file.

### CODE REVIEW

**Comment by ugursogukpinar** [comment]
Hey @KordianD, nice catch! Let me share my thoughts.

1- ARFF files have a header section which describes the columns of data -their types, possible values etc.- like this:
 
```
   @ATTRIBUTE sepallength  NUMERIC
   @ATTRIBUTE sepalwidth   NUMERIC
   @ATTRIBUTE petallength  NUMERIC
   @ATTRIBUTE petalwidth   NUMERIC
   @ATTRIBUTE class        {Iris-setosa,Iris-versicolor,Iris-virginica}
```
Do you think it's a good idea to skip that part? I am just trying to understand use cases.

2- If we are going to use a csv file without labels, the package still takes the first row as header `(csv2arff.py:29)` and tries to print it`(csv2arff.py:83)`. That would be great if you can add `is_without_labels` check into the that parts.

Thank you!

**Comment by KordianD** [comment]
After my changes when you use this on csv without labels like this:
```
0 0 1
1 1 0
1 1 1
0 0 0
```
You will get arff file like this:
```
@relation file_name
@attribute 0 numeric
@attribute 0 numeric
@attribute 1 numeric
@data
0,0,1
1,1,0
1,1,1
0,0,0
```
Personally, I would leave it as it is right now. (not removing writing attributes from first line)
I am not an expert but maybe information about "numeric" may be useful to someone someday.

**Comment by ugursogukpinar** [comment]
Showing column type is a good idea but showing first row of data as header may be confusing. How about if we put column index when label is not presented? For example: 

Input:
```
a, a, 0
a, b, 1
b, b, 1
b, a, 1
```
Output: 
```
@relation file_name

@attribute col1 {a, b}
@attribute col2 {a, b}
@attribute col3 numeric

@data
a, a, 0
a, b, 1
b, b, 1
b, a, 1
```

**Comment by KordianD** [comment]
I have updated PR
Right now for:
```
0 0 1
1 1 0
1 1 1
0 0 0
```

We get:
```
@relation file_name
 
@attribute col0 numeric
@attribute col1 numeric
@attribute col2 numeric
@data
0,0,1
1,1,0
1,1,1
0,0,0
```

**Comment by ugursogukpinar** [comment]
It looks great. Thank you!!

**Pull request merged**
